### ISSUE TITLE
Showcase search broken?

### ISSUE THREAD

**Issue by Jaifroid** [GoogleChromeLabs/fugu-showcase#6]
I understand there was a migration to a new CMS, but many apps are not appearing via search in the showcase. Try searching for 1tuner or kiwix, for example.

**Comment by tomayac** [comment]
This is a known issue with the data pipeline. We're looking into it. Meanwhile, the [debug view](https://googlechromelabs.github.io/fugu-showcase/data/) of the Fugu Showcase still works, so if you need to access the data (or just want to be sure no data loss happened), feel free to use this view as a temporary workaround.

**Comment by Jaifroid** [comment]
Just to update this -- belatedly -- I can now search for 1tuner and Kiwix successfully. 😊

**Comment by tomayac** [comment]
Thanks for confirming that it's working again.
